spring:
  datasource:
      url: jdbc:mysql://129.28.192.214:3306/shiro?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: Include_123456

mybatis:
   mapperLocations: classpath:/mapper/*.xml

server:
  port: 8080
